/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Funciones.funciones;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author sergi
 */
public class frm_interfaz extends javax.swing.JFrame {
        File archivo;
        FileWriter escribir;
        PrintWriter linea;

    /**
     * Creates new form frm_interfaz
     */
    funciones operaciones;
    public frm_interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_por = new javax.swing.JButton();
        btn_entre = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        txt_panel = new javax.swing.JTextField();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        menu_barra = new javax.swing.JMenuBar();
        menu_opciones = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_historial = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_9.setBackground(new java.awt.Color(238, 238, 238));
        btn_9.setText("9");
        btn_9.setBorder(null);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(238, 238, 238));
        btn_0.setText("0");
        btn_0.setBorder(null);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_mas.setBackground(new java.awt.Color(238, 238, 238));
        btn_mas.setText("+");
        btn_mas.setBorder(null);
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(238, 238, 238));
        btn_menos.setText("-");
        btn_menos.setBorder(null);
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_por.setBackground(new java.awt.Color(238, 238, 238));
        btn_por.setText("*");
        btn_por.setBorder(null);
        btn_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porActionPerformed(evt);
            }
        });

        btn_entre.setBackground(new java.awt.Color(238, 238, 238));
        btn_entre.setText("/");
        btn_entre.setBorder(null);
        btn_entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entreActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(238, 238, 238));
        btn_punto.setText(".");
        btn_punto.setBorder(null);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(238, 238, 238));
        btn_igual.setText("=");
        btn_igual.setBorder(null);
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        txt_panel.setBackground(new java.awt.Color(238, 238, 238));
        txt_panel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_panel.setBorder(null);
        txt_panel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_panelKeyTyped(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(238, 238, 238));
        btn_1.setText("1");
        btn_1.setBorder(null);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(238, 238, 238));
        btn_2.setText("2");
        btn_2.setBorder(null);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(238, 238, 238));
        btn_3.setText("3");
        btn_3.setBorder(null);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(238, 238, 238));
        btn_4.setText("4");
        btn_4.setBorder(null);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(238, 238, 238));
        btn_5.setText("5");
        btn_5.setBorder(null);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(238, 238, 238));
        btn_6.setText("6");
        btn_6.setBorder(null);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(238, 238, 238));
        btn_7.setText("7");
        btn_7.setBorder(null);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(238, 238, 238));
        btn_8.setText("8");
        btn_8.setBorder(null);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        menu_opciones.setText("Opciones");

        menu_nuevo.setText("Nuevo");
        menu_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevoActionPerformed(evt);
            }
        });
        menu_opciones.add(menu_nuevo);

        menu_historial.setText("Historial");
        menu_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_historialActionPerformed(evt);
            }
        });
        menu_opciones.add(menu_historial);

        menu_barra.add(menu_opciones);

        menu_ayuda.setText("Ayuda");

        jMenuItem1.setText("menu_mu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_ayuda.add(jMenuItem1);

        menu_barra.add(menu_ayuda);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_entre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_entre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed

        txt_panel.setText(txt_panel.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
    
        txt_panel.setText(txt_panel.getText()+"0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        operaciones = new funciones();
        operaciones.num_1=Float.parseFloat(txt_panel.getText());
        operaciones.op = "+";
        txt_panel.setText("");
        archivo = new File("BitacoraCalculadora.txt");
        if (!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            try {
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed

        operaciones = new funciones();
        operaciones.num_1=Float.parseFloat(txt_panel.getText());
        operaciones.op = "-";
        txt_panel.setText("");
        archivo = new File("BitacoraCalculadora.txt");
        if (!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            try {
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porActionPerformed

        operaciones = new funciones();
        operaciones.num_1=Float.parseFloat(txt_panel.getText());
        operaciones.op = "*";
        txt_panel.setText("");
        archivo = new File("BitacoraCalculadora.txt");
        if (!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            try {
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btn_porActionPerformed

    private void btn_entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entreActionPerformed

        operaciones = new funciones();
        operaciones.num_1=Float.parseFloat(txt_panel.getText());
        operaciones.op = "/";
        archivo = new File("BitacoraCalculadora.txt");
        txt_panel.setText("");
        if (!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            try {
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(operaciones.num_1);
                linea.println(operaciones.op);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btn_entreActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed

        if(!(txt_panel.getText().contains("."))){
            txt_panel.setText(txt_panel.getText()+".");
        }
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed

        operaciones.num_2=Float.parseFloat(txt_panel.getText());
        
        switch (operaciones.op){
            case "+":
                operaciones.res = operaciones.num_1+operaciones.num_2;
                txt_panel.setText(Float.toString(operaciones.res));
                archivo = new File("BitacoraCalculadora.txt");
                if (!archivo.exists()){
                    try {
                        archivo.createNewFile();
                        escribir = new FileWriter(archivo,true);
                        linea = new PrintWriter(escribir);
                        linea.println(operaciones.num_2);
                        linea.println(operaciones.res);
                        linea.close();
                        escribir.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
        
                    }else{
                            try {
                                escribir = new FileWriter(archivo,true);
                                linea = new PrintWriter(escribir);
                                linea.println(operaciones.num_2);
                                linea.println(operaciones.res);
                                linea.close();
                                escribir.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
        }
            break;
            case "-":
                operaciones.res = operaciones.num_1-operaciones.num_2;
                txt_panel.setText(Float.toString(operaciones.res));
                archivo = new File("BitacoraCalculadora.txt");
                if (!archivo.exists()){
                    try {
                        archivo.createNewFile();
                        escribir = new FileWriter(archivo,true);
                        linea = new PrintWriter(escribir);
                        linea.println(operaciones.num_2);
                        linea.println(operaciones.res);
                        linea.close();
                        escribir.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
        
                    }else{
                            try {
                                escribir = new FileWriter(archivo,true);
                                linea = new PrintWriter(escribir);
                                linea.println(operaciones.num_2);
                                linea.println(operaciones.res);
                                linea.close();
                                escribir.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
        }
                
            break;
            case "/":
                operaciones.res = operaciones.num_1/operaciones.num_2;
                txt_panel.setText(Float.toString(operaciones.res));
                archivo = new File("BitacoraCalculadora.txt");
                if (!archivo.exists()){
                    try {
                        archivo.createNewFile();
                        escribir = new FileWriter(archivo,true);
                        linea = new PrintWriter(escribir);
                        linea.println(operaciones.num_2);
                        linea.println(operaciones.res);
                        linea.close();
                        escribir.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
        
                    }else{
                            try {
                                escribir = new FileWriter(archivo,true);
                                linea = new PrintWriter(escribir);
                                linea.println(operaciones.num_2);
                                linea.println(operaciones.res);
                                linea.close();
                                escribir.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
        }
            break;
            case "*":
                operaciones.res = operaciones.num_1*operaciones.num_2;
                txt_panel.setText(Float.toString(operaciones.res));
                archivo = new File("BitacoraCalculadora.txt");
                if (!archivo.exists()){
                    try {
                        archivo.createNewFile();
                        escribir = new FileWriter(archivo,true);
                        linea = new PrintWriter(escribir);
                        linea.println(operaciones.num_2);
                        linea.println(operaciones.res);
                        linea.close();
                        escribir.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
        
                    }else{
                            try {
                                escribir = new FileWriter(archivo,true);
                                linea = new PrintWriter(escribir);
                                linea.println(operaciones.num_2);
                                linea.println(operaciones.res);
                                linea.close();
                                escribir.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
        }

        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed

        txt_panel.setText(txt_panel.getText()+"1");
        btn_1setMnemonic(KeyEvent.VK_1);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed

        txt_panel.setText(txt_panel.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed

        txt_panel.setText(txt_panel.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed

        txt_panel.setText(txt_panel.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed

        txt_panel.setText(txt_panel.getText()+"5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed

        txt_panel.setText(txt_panel.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed

        txt_panel.setText(txt_panel.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed

        txt_panel.setText(txt_panel.getText()+"8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void menu_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoActionPerformed
        // TODO add your handling code here:
        txt_panel.setText("");
        archivo = new File("BitacoraCalculadora.txt");
                if (!archivo.exists()){
                    try {
                        archivo.createNewFile();
                        escribir = new FileWriter(archivo,true);
                        linea = new PrintWriter(escribir);
                        linea.println("Nuevo");
                        linea.close();
                        escribir.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
        
                    }else{
                            try {
                                escribir = new FileWriter(archivo,true);
                                linea = new PrintWriter(escribir);
                                linea.println("Nuevo");
                                linea.close();
                                escribir.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                            }
            
        }
    }//GEN-LAST:event_menu_nuevoActionPerformed

    
    private void menu_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_historialActionPerformed
        // TODO add your handling code here:
        frm_historial frm = new frm_historial();
        frm.show();
    }//GEN-LAST:event_menu_historialActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frm_manual frm = new frm_manual();
        frm.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_interfaz().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_entre;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_por;
    private javax.swing.JButton btn_punto;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu_ayuda;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenuItem menu_historial;
    private javax.swing.JMenuItem menu_nuevo;
    private javax.swing.JMenu menu_opciones;
    public static javax.swing.JTextField txt_panel;
    // End of variables declaration//GEN-END:variables
}
